// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Qwiki.Models;

#nullable disable

namespace Qwiki.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240809125350_Initial migration")]
    partial class Initialmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.20");

            modelBuilder.Entity("Qmenu.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Published")
                        .HasColumnType("TEXT");

                    b.Property<string>("Thumbnail")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "First landing wiki page in production.",
                            Published = new DateTime(2024, 8, 9, 12, 53, 50, 873, DateTimeKind.Utc).AddTicks(616),
                            Thumbnail = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Wikipedia-logo_ka.png/600px-Wikipedia-logo_ka.png?20150720233507",
                            Title = "First wiki page"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
